### ISSUE TITLE
Radio puzzle todos

### ISSUE THREAD

**Issue by voelkerb** [ubilab-ws21/esclab#11]
- [x] turn on with MQTT message
- [x] change noise when antenna is turned
- [x] enter button for frequency change 
- [x] fix wired behaviour when inserting "manual"
- [x] finalize hardware (enclosure)

**Comment by Henrike96** [comment]
- [ ] turn on with MQTT message -- in work
- [ ] change noise when antenna is turned -- in work
- [x] enter button for frequency change
- [x] fix wired behaviour when inserting "manual"
- [ ] finalize hardware (enclosure) -- in work

**Comment by voelkerb** [comment]
Perfect - thanks for the update

**Comment by Henrike96** [comment]
- [x] turn on with MQTT message
- [x] change noise when antenna is turned 
- [x] enter button for frequency change
- [x] fix wired behaviour when inserting "manual"
- [x] finalize hardware (enclosure)

**Comment by voelkerb** [comment]
Perfect! If you have finalized the box, just close this issue ;)

**Comment by Henrike96** [comment]
I can't find the Button to do so. Maybe I don't have the rights for closing the issue? Or I am blind...
