### ISSUE TITLE
Knock knock puzzle

### ISSUE THREAD

**Issue by voelkerb** [ubilab-ws21/esclab#13]
So basically the puzzle is not working yet, right?
I see a lot of todos left given only 2 weeks of time remaining:

- [ ] box must be more rigid
- [ ] finish hardware to open the box 
- [ ] finish hardware for the lights puzzle (currently only on breadboard) 
- [ ] implement knock knock feature
- [ ] get current time left (I think there is currently no mqtt message for this)

Story wise
- [ ] indicate that knock has sth. to do with the current time left

**Comment by voelkerb** [comment]
@Group: Any news here?

**Comment by hanras97** [comment]
We demonstrated our puzzle today. We were pointed out a few minor changes that have to be made. We are working on it. And regarding MQTT, we have modified our code to parse JSON messages and it is working fine. We will be using the topics "2/esp" and "game/puzzle2" to communicate with the operator and ARscape resp.

**Comment by voelkerb** [comment]
Okay sounds perfect! Then we can close this issue
