### ISSUE TITLE
Make text to speech working again

### ISSUE THREAD

**Issue by voelkerb** [ubilab-ws21/esclab#3]
Stuff todo:
- [x] connect speaker and install speaker in other room
- [x] can we then address them separately (is this required anyway)?
- [x] amazon stuff?
- [x] mp3 playback still supported?
- [x] fix software audio device
- [x] test

**Comment by sboettcher** [comment]
Code + readme: https://github.com/ubilab-escape/environment/tree/master/text_to_speech

To use AWS Polly it requires an AWS account that hasn't registered it for over a year. I'll check if mine is still eligible.

**Comment by pscholl** [comment]
https://github.com/Iiridayn/pico-tts

ist wohl die engine aus android. 

echo "Hoooooooray You saved Freiburg." | pico-tts | ffmpeg -f s16le -ar 16000 -i - -y ah.mp4

Naja, klingt okay, aber im browser geht das grad nicht (also in meinem)

https://user-images.githubusercontent.com/223125/151590205-f33e70e8-52bc-4e23-8ad3-8c7caa811368.mp4
